Reproducible Research: Peer Assessment 1
==============================================

## Loading and preprocessing the data
```{r Block1}
setwd("C:/Users/ccortes/Documents/GitHub/RepData_PeerAssessment1")
zfile <- "C:/Users/ccortes/Documents/GitHub/RepData_PeerAssessment1/activity.zip"
dfile <- "C:/Users/ccortes/Documents/GitHub/RepData_PeerAssessment1/activity.csv"
if(!file.exists(dfile)) {
        unzip(zfile, exdir='.')
}
activity <- read.csv(dfile, header = TRUE)

```

## What is mean total number of steps taken per day?
```{r Block2}
# Rows with values (not NA)
a <- activity[!is.na(activity$steps),]

# 1) Calculate the total number of steps taken per day
a_date <- aggregate(x = a[,c("steps")], by = list(a$date), FUN = "sum")
names(a_date) <- c("date", "steps")

# 2) Make a histogram of the total number of steps taken each day
hist(a_date$steps, main = "Total Number of Steps per day", xlab = "Steps per day", col = "red")

# 3) Calculate and report the mean and median of the total number of steps taken per day
mean(a_date$steps)
median(a_date$steps)

```

## What is the average daily activity pattern?
```{r Block3}
# Grouping by interval with mean of steps
a_int <- aggregate(x = a[,c("steps")], by = list(a$interval), FUN = "mean")
names(a_int) <- c("interval", "mean")

# 1) Make a time series plot of the 5-minute interval (x-axis) and the average number of steps taken, 
#    averaged across all days (y-axis)
plot(a_int$interval, a_int$mean, type="l" , xlab = "5 minute interval", ylab = "Average step taken")

# 2) Which 5-minute interval, on average across all the days in the dataset, contains the maximum number of steps?
a_int[a_int$mean == max(a_int$mean), "interval"]

```

## Imputing missing values
```{r Block4}
# Rows without value (na)
# 1) Calculate and report the total number of missing values in the dataset (i.e. the total number of rows with NAs)
a_na  <- activity[is.na(activity$steps),]
str(a_na)

# 2) Devise a strategy for filling in all of the missing values in the dataset. 
#    The strategy does not need to be sophisticated. 
#    For example, you could use the mean/median for that day, 
#    or the mean for that 5-minute interval, etc.

# Merging a_na (with NA values in a_na$steps) with a_int to get the mean steps by interval and replace the empty a_na$steps
a_na1 <- merge(a_na, a_int, by.x = c("interval"), by.y = c("interval"))
a_na_fill <- data.frame(round(a_na1$mean), a_na1$date, a_na1$interval)
names(a_na_fill) <- c("steps", "date", "interval")

# 3) Create a new dataset that is equal to the original dataset but with the missing data filled in.
a_fill <- rbind(a, a_na_fill)

# 4) Make a histogram of the total number of steps taken each day and 
#    Calculate and report the mean and median total number of steps taken per day. 
#    Do these values differ from the estimates from the first part of the assignment? 
#    What is the impact of imputing missing data on the estimates of the total daily number of steps?

# Grouping by date with total steps
a_filled <- aggregate(x = a_fill[,c("steps")], by = list(a_fill$date), FUN = "sum")
names(a_filled) <- c("date", "steps")

hist(a_filled$steps, main = "Total Number of Steps per day", xlab = "Steps per day", col = "blue")
mean(a_filled$steps)
median(a_filled$steps)

```


## Are there differences in activity patterns between weekdays and weekends?
```{r Block5}
# 1) Create a new factor variable in the dataset with two levels - "weekday" and "weekend" 
#    indicating whether a given date is a weekday or weekend day
# Adding week_day factor new column  
a_fill$week_day <- as.factor(ifelse(weekdays(as.Date(a_fill$date)) == "Saturday" | weekdays(as.Date(a_fill$date)) == "Sunday", "weekend", "weekday"))
```

```{r Block6, fig.height = 4, fig.width = 6 }
# Grouping by interval with mean of steps
a_fill_int <- aggregate(x = a_fill[,c("steps")], by = list(a_fill$interval, a_fill$week_day), FUN = "mean")
names(a_fill_int) <- c("interval", "week_day", "Number_of_steps")
# 2) Make a panel plot containing a time series plot (i.e. type = "l") of the 5-minute interval (x-axis) 
#    and the average number of steps taken, averaged across all weekday days or weekend days (y-axis). 

require(ggplot2)
ggplot(a_fill_int, aes(interval, Number_of_steps)) + geom_line(colour = "blue") + facet_grid(week_day ~.)

```
